on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: test
      run: go test -race ./...
